<?php 
if (isset($_POST['submit'])) {

abstract class Person {

    protected $list = array("adam", "jan", "tomas", "dusan", "igor", "viera", "tana", "zoltan", "oskar", "laco", "peto", "juro", "lubo", "dagmara" );

    protected function getList(){

        return $this->list;
    }
}

class Main extends Person {

    public $roles;
    public static $role_list = array( "1" => "tana", "2" => "tomas", "3" => "viera", "4" => "zoltan", "5" => "peto", "6" => "tomas", "7" => "juro", "8" => "igor", "9" => "lubo", "10" => "oskar", "11" => "jan" );
    public function __construct( array $roles = array() ) {
        $this->roles = $roles;
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

}

class Work {

    public $list = array('kim' => 'grafik', 'igor' => 'TL', 'paolo' => 'qa');
    public $roles = array( "3" => "grafik", "5" => "developer", "9" => "builder", "1" => "qa", "2" => "wdl", "4" => "wpl", "11" => "gwdl", "10" => "TL", "8" => "PM", "7" => "architekt", "6" => "FA" );
}


class View {
	
	public function render( $table ){
	
	}
	
}

$ob = new View; // create an object of view class
$listWork = new Main;
$work = new Work; // create an object of work class
//print_r($work->list);
//print_r($work->roles);
///$listWork->roles = $roles;
//print_r($listWork->roles);
//print_r($listWork::$role_list);
//print_r($listWork->getList());

$person = $listWork->getList();
$rolesArrray = $work->roles;
$loop1=0;
$loop2=0;
echo "<div class='result' id='result'><table border='1'>";
echo "<th>Person Name</th>";
foreach ($listWork->getList() as $k => $v){
		$i=1;
		//echo $v;
		foreach ($work->roles as $key => $value){
		 
		
		if ($i==1) {
		
		
		 if ($k != $key)
			 {
			 $value="";
			
			 }
		 if ($key == $k) 
			 {
			 $v="";
			 $value="";
			 }
		 if ($k==0 || $k==12 || $k==13) {
			$i=$i+1;
		echo "<tr><td>".$v."</td></tr>";
			
				
			}
	   
		}
		
    }

}
echo "</table></div>";

}




?>
<style>
table {
  border-collapse: collapse;
  width: 30%;
}

th, td {
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {background-color: #f2f2f2;}
</style>



<form method="POST" action="">

<input type="submit" name="submit" id="submit" value="RESULT">

</form>


