<?php

abstract class Person {

    protected $list = array("adam", "jan", "tomas", "dusan", "igor", "viera", "tana", "zoltan", "oskar", "laco", "peto", "juro", "lubo", "dagmara" );

    protected function getList(){

        return $this->list;
    }
}

class Main extends Person {

    public $roles;
    public static $role_list = array( "1" => "tana", "2" => "tomas", "3" => "viera", "4" => "zoltan", "5" => "peto", "6" => "tomas", "7" => "juro", "8" => "igor", "9" => "lubo", "10" => "oskar", "11" => "jan" );
    public function __construct( array $roles = array() ) {
        $this->roles = $roles;
    }

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

}

class Work {

    public $list = array('kim' => 'grafik', 'igor' => 'TL', 'paolo' => 'qa');
    public $roles = array( "3" => "grafik", "5" => "developer", "9" => "builder", "1" => "qa", "2" => "wdl", "4" => "wpl", "11" => "gwdl", "10" => "TL", "8" => "PM", "7" => "architekt", "6" => "FA" );
}


class View {
	
	public function render( $table ){
		$html = "
         <html>
        <head>
        <script src='jquery-core-latest.js' type='text/javascript' ></script>
        </head>
        <body>
        <form method='get' action=''>
        <input type='submit' name='submit' value='submit' />
        <div id='results'>
        </div>
        </form>
        </body>
        </html>
";
	}
	
}

$ob = new View; // create an object of view class
$listWork = new Main;
$work = new Work; // create an object of work class

$person = $listWork->getList();
$rolesArrray = $work->roles;


echo "<table border='1'>";
echo "<th>Person Name</th>"."<th>Role</th>";
foreach ($listWork->getList() as $k => $v){
			foreach ($work->roles as $key => $value){
        if($k==$key){
            echo "<tr><td>".($v)."</td><td>".$value."</td></tr>";
        }
    }
}
echo "</table>";
